services:
  - type: web
    name: horuseye-api
    runtime: docker
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: horuseye-db
          property: connectionString
      - key: Jwt__Key
        sync: false
      - key: Jwt__Issuer
        value: HorusEyeAPI
      - key: Jwt__Audience
        value: HorusEyeFrontend
databases:
  - name: horuseye-db
    plan: free
    databaseName: horuseyedb
    user: horuseyeuser
