services:
  - type: web
    name: horuseye-api
    runtime: docker
    plan: free
    branch: main
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d8c5nau7r5hc7394c4dg-a;Port=5432;Database=horuseyedb;Username=horuseyeuser;Password=mrHb3sSNsvcsFAYHKU5Wn9R6U2AjF6Iq
      - key: Jwt__Key
        value: HorusEyeSuperSecretKey2026!@#$%^&*()VeryLongSecure
      - key: Jwt__Issuer
        value: HorusEyeAPI
      - key: Jwt__Audience
        value: HorusEyeFrontend
databases:
  - name: horuseye-db
    plan: free
    databaseName: horuseyedb
    user: horuseyeuser
